name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev"]

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.15.0-dev'
        otp-version: '25'

    - name: Restore dependencies
      run: mix deps.get

    - name: Run tests
      env:
        MIX_ENV: test
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/my_app_test
      run: mix test
